### ISSUE TITLE
Object.entries is not a function error at InjectManifest plugin

### ISSUE THREAD

**Issue by EnigmaGun** [yandeu/phaser-project-template#1]
First of all thanks a lot for this great template!

After pulling the latest version I receive following error when running the template:

× ｢wdm｣: TypeError: Object.entries is not a function
    at generateMetadataForAssets (C:\WorkspaceTest\phaser-project-template\node_modules\workbox-webpack-plugin\build\lib\get-manifest-entries-from-compilation.js:171:22)
    at getManifestEntriesFromCompilation (C:\WorkspaceTest\phaser-project-template\node_modules\workbox-webpack-plugin\build\lib\get-manifest-entries-from-compilation.js:232:25)
    at C:\WorkspaceTest\phaser-project-template\node_modules\workbox-webpack-plugin\build\inject-manifest.js:96:21
    at next (native)
    at asyncGeneratorStep (C:\WorkspaceTest\phaser-project-template\node_modules\workbox-webpack-plugin\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\WorkspaceTest\phaser-project-template\node_modules\workbox-webpack-plugin\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)

After commenting the InjectManifest plugin in webpack.common.js I was able to run the template.

**Comment by yandeu** [comment]
Thanks for letting me know.

On my system it works (Ubuntu 16.04, Node 10.15.3 )

I have found this: https://stackoverflow.com/a/50776623

What version of node do you use? `node -v`

**Comment by EnigmaGun** [comment]
Thanks a lot for the fast answer and sorry, I could have figured this out by myself!
I actually used node version 6 and after upgrading to the last version it works fine now!
Thanks!
